micronaut:
  application:
    name: jetBrainsInternShipTask
  server:
    cors:
      enabled: true
jackson:
  bean-introspection-module: true

datasources:
  default:
    url: jdbc:postgresql://ec2-54-73-58-75.eu-west-1.compute.amazonaws.com:5432/d49u7a3v71rso4
    driverClassName: org.postgresql.Driver
    username: scvishmfbjqciu
    password: b1695457d0d7b133f22d160ef961244999f32293ce441cbe5f82b63b18625a4e

jpa:
  default:
    packages-to-scan:
      - 'mishaninnikita'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true