micronaut:
  application:
    name: jetBrainsInternShipTask
  server:
    cors:
      enabled: true

datasources:
  default:
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

application:
  max: 50

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true